server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingservice
    username: postgres
    password: Qwerty1,0*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true